### ISSUE TITLE
可以的话尽量用 GitHub 来提供下载。

### ISSUE THREAD

**Issue by wclebb** [MichaelRow/Lyrics#11]
并非所有人都乐意和使用 BaiDu 网盘的。
如果你能简单提供放到 GtiHub 我会很感激你这样做。

虽然从 1.1.8 版本之后改为百度网盘。

**Comment by kxxoling** [comment]
能从 brew cask 安装就更好了，DynamicLyrics 就支持 cask 安装方式。
