### ISSUE TITLE
无法搜索歌词和封面图LrcSeeker崩毁

### ISSUE THREAD

**Issue by liulipeng** [MichaelRow/Lyrics#19]
系统版本10.12.3

**Comment by bbbear2002** [comment]
应该是和 2016 RMBP TouchBar 有冲突，我的也崩溃了

**Comment by LiShengmin** [comment]
搜索歌词封面应该是，界面应该逻辑应该没问题，一会看下哪里出的问题吧。再来报告

**Comment by LiShengmin** [comment]
定位最后抛出的是AppController的366行NSWorkspace.shared().launchApplication(appPath)这句话..貌似是启动LrcSeeker.app的时候出的问题，没有找到LrcSeeker的源码没法继续下去了。。

**Comment by MichaelRow** [comment]
你好，2.0版本已经重构，目前正在开发中，1.x中的bug会解决
