### ISSUE TITLE
针对自动检测全屏的建议

### ISSUE THREAD

**Issue by latestlu** [MichaelRow/Lyrics#2]
对自动检测全屏，我现在遇到的问题是，我在左右切换桌面时，会交替被判断为全屏和未全屏，即虽然在当前桌面我校准了全屏模式，但切换桌面后，依然需要校准，解释起来比较费劲，测试一下切换桌面即可知。
若当前还无法做到自动检测全屏，建议由用户手动设置全屏模式，默认非全屏模式。这样，即便处于全屏模式，歌词无非高一点，但不会被遮挡住，影响使用。

**Comment by MichaelRow** [comment]
在实现自动检测之前，我会暂时采纳这个建议，谢谢反馈，并对于测试的不充分抱歉。由于现在出门在外，手头没有Mac，可能要过几天修复，还请稍等。

**Comment by latestlu** [comment]
客气了，毕竟也是我需要的，算是帮我自己，以前一直用DynamicLyrics，一直在找能接替的软件，这个恰好是我的需求，其实也要谢谢你提供免费实用的软件。

**Comment by MichaelRow** [comment]
重新修改了下，现在可以歌词的高低可以通过菜单栏调节。
