### ISSUE TITLE
超棒的軟體，可以加入更多功能嗎？

### ISSUE THREAD

**Issue by houtacheng** [MichaelRow/Lyrics#21]
類似千千靜聽的歌詞功能：
1.以歌詞為主播方式：點到哪一句歌詞就從哪裡開始播放
2.歌詞中可搜尋關鍵字
3.卡拉ＯＫ模式

http://tzoyiing.pixnet.net/blog/post/22737126-%E5%85%8D%E8%B2%BB%E8%BB%9F%E9%AB%94%E5%88%86%E4%BA%AB%EF%BC%9A%E9%9F%B3%E6%A8%82%E6%92%AD%E6%94%BE%E5%99%A8%EF%BC%8D%E5%8D%83%E5%8D%83%E9%9D%9C%E8%81%BD-v5.3-%E7%B0%A1

**Comment by MichaelRow** [comment]
2.0中會新增更多的功能，目前還在開發中
