### ISSUE TITLE
软件还会有更新吗

### ISSUE THREAD

**Issue by bbbear2002** [MichaelRow/Lyrics#24]
应对 RMBP 2016 的 Lyrics Seeker 崩溃，请问作者还有考虑更新吗？

**Comment by ddddxxx** [comment]
作者不接受pr，我重写了一个，地址 https://github.com/XQS6LB3A/LyricsX

**Comment by bbbear2002** [comment]
@XQS6LB3A ，这个好啊，又简洁又美观，很苹果，赞一个！

**Comment by ddddxxx** [comment]
@bbbear2002 目前正在快速迭代，请注意检查更新。有任何意见和建议欢迎提issue和pr

**Comment by bbbear2002** [comment]
@XQS6LB3A 好的，严重支持

**Comment by LiShengmin** [comment]
@XQS6LB3A 之前研究这个的源码发现调用了一个已经打包的文件，回去看看你的，真棒！

**Comment by MichaelRow** [comment]
重写中，由于之前的代码太烂了，自己都看不下去了。很快就会完成2.0版本，会支持逐字歌词，以及更多的歌词源，整个应用已经重构了
