### ISSUE TITLE
制作歌词时不能播放啊

### ISSUE THREAD

**Issue by vanabel** [MichaelRow/Lyrics#26]
肯定是个bug吧， 首先歌词搜索不太准确，然后想自己制作却又不能添加时间线

**Comment by MichaelRow** [comment]
你好，能提供详细信息吗？
另外，整个LyricsX在重写中，之后会支持逐字歌词，时间线可以精确到字。歌词的搜索源会加入网易和酷狗的逐字歌词，搜索精确度会提高

**Comment by vanabel** [comment]
已经比较详细了吧， 不知道还有哪些信息？

刚刚在听 你在终点等我
自动歌词搜不到（这里搜出来的结果好像歌名和歌手反了）
就想着自己制作一个吧
然后点击歌词／制作歌词
弹出制作界面／自动填入歌曲信息（ok）／然后copy网络搜到的歌词／下一步
这时应该是按空格键试听歌曲／按下箭头插入时间线／
试听按空格键没反应

Mac 系统是最新的10.12.6

感觉是个bug

最后其实这个插件用着挺好的，所以才来提个issue

**Comment by MichaelRow** [comment]
2.0 修复
