### ISSUE TITLE
改用musixmatch的api会比现在识别率高很多，现在欧美歌的识别率太低了

### ISSUE THREAD

**Issue by stevewongv** [MichaelRow/Lyrics#3]
建议https://developer.musixmatch.com/documentation，欧美的歌库很足，能解决qq音乐部分歌词获取不了的问题。

**Comment by MichaelRow** [comment]
谢谢反馈。目前问题还是比较多的，由于目前使用的大多是各大平台非公开的API，质量参差不齐。不仅仅是QQ音乐，其他的源也一样，返回数据包部分是有歌词/专辑封面的（有些是密文有些是明文），部分是没有的。识别率低一直也是个问题，因为搜索是模糊搜索，难免获取到错误的歌词，之后会改进用于搜索的关键字，并且将歌词和专辑封面搜索分开来。至于上面提供的musixMatch API，貌似是没带时间轴的，不能做到同步显示，不过我可以把它应用在LrcMarker上，让用户自行制作时间轴。最近可能没时间，在做iOS平台的一个毕设，之后有时间了再修改

**Comment by stevewongv** [comment]
我看了他提供的例子好像是有时间轴的，之前学了一段时间swift后来又荒废了😂自己完成不了只能交给你啦🌝加油。毕设重要，不急~

**Comment by MichaelRow** [comment]
我可能没仔细看吧，有时间轴就好办了，至于是什么格式倒不重要，都可以正则匹配出歌词部分时间部分。

**Comment by bbbear2002** [comment]
好像虾米音乐的歌词准确度最高，建议新版本优先使用虾米的歌词

**Comment by LiShengmin** [comment]
我看了源码，觉得好多地方没看懂，可能是没搞过OSX的开发。。希望可以学习～并帮助一起改进源码
