### ISSUE TITLE
希望可以增强搜索(自动导入)本地歌词的功能

### ISSUE THREAD

**Issue by wu67** [MichaelRow/Lyrics#4]
原因如下：
作为歌词强迫症患者，已经将很多满意的歌词保存在本地了，不同使用者的文件名格式可能或多或少有差别。我发现您的程序中，歌词文件是以%title% - %aritist%保存的, 实际上可以读本地歌词，假设允许设置歌词文件名的保存(读取？导入)格式，如%artist% - %title%,即可方便读取本地歌词了

**Comment by MichaelRow** [comment]
OK，这个没问题，这周有空的时候做。歌词文件的确是使用这种保存格式，如果歌词名中有"/"会替换成“&”，因为"/"会被NSFileManager理解成下一级目录。允许设置歌词文件的保存不难做到，就比如像大多数软件中，用%ti表示歌名，%al表示歌手名，%ab表示专辑，l每次更改后，将自动更新保存目录下的文件名（或者多一个数据项保存指定歌曲的歌词文件保存路径，只更新这个值）。
