### ISSUE TITLE
vox貌似不好使

### ISSUE THREAD

**Issue by peterzhangnull** [MichaelRow/Lyrics#5]
打开vox没有反应

**Comment by MichaelRow** [comment]
https://github.com/MichaelRow/Lyrics/releases/tag/v1.0-beta
只有这个版本支持

**Comment by meilbn** [comment]
@MichaelRow 
为何使用 VOX 歌词可以自动下载，但是桌面不显示歌词呢？
Display  下的 Enable Desktop Lyrics 也是选中的。
使用的就是上面的 1.0 的源码自己编译的
谢谢！

**Comment by exxfzc** [comment]
vox版本的好久不更新了,不知道还能不能用
